#ifndef __CONFIG_H_
#define __CONFIG_H_

#define WRITE_CHANNEL 1
#define READ_CHANNEL 0

#define READ_UNIDIR 0
#define WRITE_UNIDIR 1
#define READ_PARENT 0
#define WRITE_PARENT 1
#define READ_CHILD 2
#define WRITE_CHILD 3
//TODO check this
#define MAXLEN_PIPE 4096
#define MAXLEN_ERR 4096

#define RELATIVE 0
#define ABSOLUTE 1

#define GOOD_ENDING 0
#define BAD_ENDING -1

#define NOT_EMPTY 0
#define EMPTY -1

#define DIRECTORY 1
#define IS_FILE 0
#define NOT_EXISTING 2

#define SUMMARY 0
#define NEW_DIRECTIVES 1

#define FANCY_MODE 1
#define NORMAL_MODE 0

#define HOR_TABLE '-'
#define VER_TABLE '|'

#define WORKING 1
#define NOT_WORKING -1

#define INT_MAX_LEN 20
#define NCHAR_TABLE 129

#define CONTROL_WORD_LEN 5
#define CONTROL_DONE "done"
#define CONTROL_UNDONE "undo"

#define HARAKIRI -1

#define SUCCESS 0
#define FAILURE -1
#define TABLE_FAILURE -2
#define WORK_FAILURE -3
#define READ_FAILURE -4
#define END_WORK_FAILURE -5
#define NEW_DIRECTIVES_FAILURE -6
#define CAST_FAILURE -7
#define PIPE_FAILURE -8
#define SUMMARY_FAILURE -9
#define REMOVE_WORK_FAILURE -10
#define INIT_FAILURE -11
#define ASSIGNWORK_FAILURE -12
#define SEND_FAILURE -13
#define DESCRIPTOR_FAILURE -14
#define ASSIGNWORK_MEMORY_FAILURE -15
#define DEAD_PROCESS -16
#define START_NEW_MANAGER -17
#define NEW_MANAGER_FAILURE -18
#define FORK_FAILURE -19
#define MANAGER_NULL_ERORR -20
#define ENQUEUE_MANAGER_ERROR -21
#define FILE_NULL_POINTER -22
#define CWD_FAILURE -23
#define STARTING_DIRECTORY_FAILURE -24
#define ASSIGNFILE_MEMORY_FAILURE -25
#define REMOVE_MANAGER_FAILURE -26
#define CWD_ACCESS_DENIED -27
#define ALREADY_INSERTED -28
#define EMPTY_PATH -29
#define BASH_ERROR -30
#define FILE_NOT_FOUND -31
#define NEW_WORKER_FAILURE -32
#define MALLOC_FAILURE -33
#define UNEXPECTED_LIST_ERROR -34
#define CHARACTER_OVERFLOW -35
#define NULL_POINTER -36
#define OVERRIDING_TREE -37
#define HELP_PRINT -38
#define DOUBLE_OPTION_FAILURE -39
#define GET_SIZE_FAILURE -40
#define PRINT_LOG_FAILURE -41
#define GRAPHIC_LOOP_FAILURE -42
#define INPUT_LOOP_FAILURE -43
#define READ_DIRECTIVES_FAILURE -44
#define CURSOR_FAILURE -45
#define WRITE_FAILURE -46

#endif