#!/bin/bash
lines=$(wc -l $1 | awk -F' ' '{print $1}')
for i in $(seq 1 $lines)
do
    primo=$(cat $1 | awk -F' ' '{print $1}' | sed -n ${i}p)
    bello=$(cat $1 | awk -F' ' '{print $2}' | sed -n ${i}p)
    secondo=$(cat $2 | awk -F';' '{print $2}' | sed -n ${i}p)
    figo=$(cat $2 | awk -F';' '{print $1}' | sed -n ${i}p)
    echo $primo' - '$secondo' - '$bello' - '$figo
    echo $(expr $secondo - $primo)
done
